export const products = [
  {
    id: 1,
    title: "قالب فروشگاهی حرفه‌ای ری‌اکت",
    price: 350000,
    originalPrice: 890000,
    seller: "علی محمدی",
    sellerAvatar: "/api/placeholder/40/40/0D8F81/white?text=ع",
    rating: 4.8,
    reviewCount: 124,
    // تصاویر از سرور داخلی (فیلتر نیست)
    image: "/api/placeholder/600x400/0D8F81/white?text=Web+Template",
    category: "قالب‌های وب",
    description:
      "قالب فروشگاهی مدرن و واکنش‌گرا با استفاده از React و Tailwind.",
    features: [
      "طراحی کاملاً واکنش‌گرا",
      "دارای ۵ صفحه اصلی",
      "پشتیبانی از حالت تاریک",
      "بهینه برای سئو",
    ],
    stock: 15,
    tags: ["react", "tailwind", "ecommerce"],
  },
  {
    id: 2,
    title: "پکیج آموزش Next.js از صفر تا صد",
    price: 890000,
    originalPrice: null,
    seller: "زهرا حسینی",
    sellerAvatar: "/api/placeholder/40/40/2563EB/white?text=ز",
    rating: 5,
    reviewCount: 87,
    image: "/api/placeholder/600x400/2563EB/white?text=Next.js+Course",
    category: "دوره‌های آموزشی",
    description: "دوره جامع آموزش Next.js 14 به همراه پروژه عملی مارکت‌پلیس.",
    features: [
      "۲۵ ساعت آموزش ویدیویی",
      "پروژه عملی انتهای دوره",
      "پشتیبانی ۳ ماهه",
      "دسترسی مادام‌العمر",
    ],
    stock: 50,
    tags: ["nextjs", "آموزش", "javascript"],
  },
  {
    id: 3,
    title: "کامپوننت‌های آماده Tailwind",
    price: 180000,
    originalPrice: 320000,
    seller: "محمد رضایی",
    sellerAvatar: "/api/placeholder/40/40/DC2626/white?text=م",
    rating: 4.5,
    reviewCount: 43,
    image: "/api/placeholder/600x400/DC2626/white?text=UI+Components",
    category: "کامپوننت‌ها",
    description: "مجموعه کامپوننت‌های حرفه‌ای Tailwind CSS.",
    features: [
      "۵۰+ کامپوننت آماده",
      "قابل تنظیم با Tailwind",
      "responsive",
      "دارای فایل Figma",
    ],
    stock: 200,
    tags: ["tailwind", "ui", "components"],
  },
  {
    id: 4,
    title: "اسکریپت فروشگاهی اختصاصی",
    price: 1250000,
    originalPrice: null,
    seller: "سارا نوری",
    sellerAvatar: "/api/placeholder/40/40/9333EA/white?text=س",
    rating: 4.9,
    reviewCount: 28,
    image: "/api/placeholder/600x400/9333EA/white?text=ecommerce+script",
    category: "اسکریپت‌ها",
    description: "اسکریپت کامل فروشگاهی با امکانات پرداخت.",
    features: [
      "پنل ادمین کامل",
      "سیستم تخفیف",
      "درگاه پرداخت",
      "قابل نصب روی هاست معمولی",
    ],
    stock: 8,
    tags: ["javascript", "ecommerce"],
  },
  {
    id: 5,
    title: "قالب وردپرس فروشگاهی",
    price: 450000,
    originalPrice: 750000,
    seller: "رضا کریمی",
    sellerAvatar: "/api/placeholder/40/40/EA580C/white?text=ر",
    rating: 4.6,
    reviewCount: 92,
    image: "/api/placeholder/600x400/EA580C/white?text=wordpress+Template",
    category: "قالب‌های وب",
    description: "قالب حرفه‌ای وردپرس مناسب فروشگاه‌های اینترنتی.",
    features: [
      "سازگار با ووکامرس",
      "طراحی مدرن",
      "سرعت بالا",
      "راهنمای نصب تصویری",
    ],
    stock: 30,
    tags: ["wordpress", "theme", "ecommerce"],
  },
  {
    id: 6,
    title: "پلاگین سئو حرفه‌ای",
    price: 290000,
    originalPrice: null,
    seller: "امیر مهدوی",
    sellerAvatar: "/api/placeholder/40/40/0891B2/white?text=ا",
    rating: 4.7,
    reviewCount: 56,
    image: "/api/placeholder/600x400/0891B2/white?text=SEO+Plugin",
    category: "پلاگین‌ها",
    description: "پلاگین کامل سئو برای وب‌سایت‌های فارسی.",
    features: [
      "تحلیل کلمات کلیدی",
      "سایت مپ خودکار",
      "پیشنهاد متاتگ",
      "سئو تکنیکال",
    ],
    stock: 120,
    tags: ["seo", "plugin", "wordpress"],
  },
];

export const categories = [
  { id: "all", name: "همه محصولات", icon: "📦" },
  { id: "قالب‌های وب", name: "قالب‌های وب", icon: "🎨" },
  { id: "دوره‌های آموزشی", name: "دوره‌های آموزشی", icon: "📚" },
  { id: "کامپوننت‌ها", name: "کامپوننت‌ها", icon: "🧩" },
  { id: "اسکریپت‌ها", name: "اسکریپت‌ها", icon: "⚡" },
  { id: "پلاگین‌ها", name: "پلاگین‌ها", icon: "🔌" },
];

export function getProductById(id) {
  return products.find((p) => p.id === parseInt(id));
}

export function getProductsByCategory(category) {
  if (category === "all") return products;
  return products.filter((p) => p.category === category);
}
